export const throwTestError = () => {
  throw new Error('Test Error Boundary')
}